### ISSUE TITLE
[Feature Request] Add Node v8.x support

### ISSUE THREAD

**Issue by nwhitmont** [Azure-App-Service/node#16]
As of this posting, current versions are Node.js v8.1.0 + npm v5.0.3

**Comment by nickwalkmsft** [comment]
Working on it as I type this :)

Things stalled a little bit on this as there is an open issue with npm affecting the way it runs in Docker containers. We have a workaround but need to make sure it's tested properly.

**Comment by nwhitmont** [comment]
@nickwalkmsft Sweet! thanks for the update

**Comment by lostintangent** [comment]
@nickwalkmsft Has this support been deployed? :D

**Comment by nickwalkmsft** [comment]
Ah, no - sorry for confusion, I will leave this open until it is deployed.

**Comment by nickwalkmsft** [comment]
FYI:

- We'll have node 6.11, 8.0 and 8.1 built-in images, as well as support for all of those in Kudu.
- node 6.11.0 is LTS now, so we will generally establish that as the "default" wherever relevant.
  - We won't auto-upgrade people on 6.10.x to 6.11, but a strategy for doing this kind of thing in the future is coming. You should be able to specify "just keep me on LTS" and we should do that. I'm also looking at support for more intentional version specifications, i.e. you could specify "6" and we'll keep you on the newest version of 6, or "6.10" for newest point release of 6.10. There are decisions that have to be made on the portal UI side as well.
- npm 5.0.3 will be the default for node 8.0 and 8.1 when deploying with Kudu.

Of course, this is today. Who knows what versions tomorrow will bring 😄 "Soon" is the best ETA I can give for rollout of all this.

**Comment by lostintangent** [comment]
That sounds awesome! Thanks so much for the update.

**Comment by nwhitmont** [comment]
![excellent](https://user-images.githubusercontent.com/3075047/27062363-5a55d214-4f9f-11e7-977d-b6bbe511d4c2.jpg)

**Comment by lostintangent** [comment]
@nickwalkmsft Any updates on the deployment ETA? :)

**Comment by nickwalkmsft** [comment]
Hey, I'll drop a couple updates here:

- Node 8 support is queued for our next deployment. I can't speak to exactly when that's going to be; my hope is within the week. I'll try to update if I get more information.
- We have cleaned up our strategy for managing our repos and version support, which will help greatly with our ability to keep up with new versions. Overall, including for node, the plan is to expose options for the available major versions in the portal (in node's case, this would be 4, 6 and 8). Picking one of those should keep you on the newest available release for that version, upgrading you automatically as we roll out new images. For node we may offer an "lts" option as well. This level of stability seems to have the greatest alignment with developer expectations across the board, given the nature of the service and the availability of a fully-customizable option (user-provided images). There will be a more advanced option (not available through a GUI picker) if you want to stay locked to a specific major.minor or major.minor.patch.

**Comment by lostintangent** [comment]
Sounds awesome! Thanks for the update

**Comment by lostintangent** [comment]
@nickwalkmsft Any updates?

**Comment by nwhitmont** [comment]
@nickwalkmsft what's the latest update?

**Comment by nickwalkmsft** [comment]
Apologies for the radio silence on this. Node 8.0, 8.1 and 8.2 are globally available. The selectors in the portal UX are not available yet (should be next week) but you can select them by using ARM or Azure Resource Explorer to set your site's LinuxFxVersion value to NODE|8.0, NODE|8.1 or NODE|8.2.

**Comment by nwhitmont** [comment]
In case anyone was wondering, Azure "App Service on Linux" has been renamed to "Web App for Containers" && the new "Web App" allows the user to choose between Linux & Windows OS in the creation workflow. Eg. There is no longer a stand-alone App Service for Linux as you might have see in the portal a few weeks back.

Thanks again Azure team for providing us these great developer tools!
